### PR TITLE
remove dot class make it part of the CSS

### LINKED ISSUE #516: movie details view issues
- [ ] Visually: at 960x580 (min WxH for the window), it's ugly: 
nw_2016-12-04_11-33-50

- [x] things move around when opening/closing dropdowns, they should be on top of other thing, and not make small 'jumps' in the UI

- [ ] Logs say "audio:none" but it's english. It isn't 'none'. Maybe something to set in butterproviders?

- [ ] dots should be connected to each metadata entry (year, runtime, genres, etc) so we can hide() a missing metadata element and it hides the dot at the same time

- [ ] render health is broken and is temporarily put in a try/catch

### PR DESCRIPTION
**Pull request by xaiki**
Signed-off-by: Niv Sardi <xaiki@evilgiggle.com>

Fixes #516 or at least parts of it.

### CODE REVIEW

**Comment by vankasteelj** [comment]
There's an issue with the rating stars dot, it's underlined. I couldnt find out in devtools what was causing it

**Comment by vankasteelj** [comment]
This will realign the stars, there still is the underline issue. 
```
.rating-star-half-container {
    width: 1em;
    height: 1em;
    line-height: 1em;
    margin-left: 2px;
    margin-right: -2px;
}
```

**Comment by vankasteelj** [comment]
the underline is only present in vodo movie details : wtf?

**Comment by xaiki** [comment]
@vankasteelj the bug was from the use of content: ".", fixed that and the alignments.

**Pull request merged**
