### PR TITLE
Fix cache folder when you load settings via npm

### PR DESCRIPTION
**Pull request by Bart-0110**
Without this fix the program will always use ./Temp/Butter

### CODE REVIEW

**Comment by vankasteelj** [comment]
but there's a setting for that... the goal is to allow NOT using temp. On my netbook, I only have 1GB of free space on my builtin SSD, and I can tell the app to use my SD Card instead.

**Comment by Bart-0110** [comment]
Ah okey. I forgot that you can change the temp folder.

**Comment by vankasteelj** [comment]
what was the problem with temp anyway? did it set folder at different places?

**Comment by Bart-0110** [comment]
For example:
My program name is 'Test'. When I open the app and go the the settings the default cache location is %temp%/Butter instead of %temp%/Test

**Comment by vankasteelj** [comment]
okay, can you open an issue about that? You can PR if you want too, but this way the issue isn't lost and forgotten :)

**Pull request closed without merging**
