### PR TITLE
High contrast theme

### PR DESCRIPTION
**Pull request by richardfshu**
Created high contrast theme as described in help-wanted #371

### CODE REVIEW

**Comment by ZakariaRidouh** [comment]
This looks good 😄 

Did you test it out already?

**Comment by vankasteelj** [comment]
awesome, i'll check it out!

**Comment by vankasteelj** [comment]
Great, almost perfect. The navigation icons aren't shown, top-right of the app, they need to be purple too, probably. Do you have any visual impairement or did you based off some paper on how to make "high contrast" UI ? 

Also, if you want to take it further: you can override about any css by adding a rule at the end of the file, see https://github.com/butterproject/butter-desktop/blob/master/src/app/styl/Official_-_FlaX_theme.styl#L159

**Comment by richardfshu** [comment]
I'll fix that! I do not have serious vision impairment, only myopia, so I was mainly going off of online sources. I'm hoping that the color I chose will have the right visual properties and sufficient contrast.

**Comment by HenrikoMagnifico** [comment]
I... am not sure where to post this really, since the Discussion Forum is down, but are there any news on when a simple windows .exe installer of the Butter Project will be available? Sorry for asking, since I know it will come when it comes - but still!

**Comment by vankasteelj** [comment]
@richardfshu any news?

**Comment by vankasteelj** [comment]
:'(

**Comment by xaiki** [comment]
@vankasteelj should we get that in, better that than nothing ?

**Comment by vankasteelj** [comment]
I don't know, I don't want to make a decision.

**Pull request merged**
