### PR TITLE
Remove mouseScroll listner event

### PR DESCRIPTION
**Pull request by chtrinh**
`.bind()` returns a new function which is not referenced
when trying to removed later. Saving bounded function as a property
to be referenced.

### CODE REVIEW

**Comment by xaiki** [comment]
looks good to me, but i'll let @vankasteelj review this one, he knows better the code.

**Comment by vankasteelj** [comment]
it seems ok. I don't know enough about events to have something to say about this, it does work, and it removes a jquery call. I'm up for that. And if it indeed correctly unbinds the event, it's even better.

**Comment by chtrinh** [comment]
If you start the player and then close it. Scrolling right afterwards
trigger an error message in your dev tools

**Comment by vankasteelj** [comment]
that's what that message was? lol

**Comment by vankasteelj** [comment]
I thought it was javascript fucking up, simply :D

**Comment by chtrinh** [comment]
@vankasteelj: 😆 , i thought so too!

**Pull request merged**
