### PR TITLE
Use opensubtitles for movies

### PR DESCRIPTION
**Pull request by vankasteelj**
basic implementation, it "works" but isn't fancy

### CODE REVIEW

**Comment by vankasteelj** [comment]
ofc, it uses the same system as tv, without loading subs on details, only on loading screen.

**Comment by xaiki** [comment]
this should be using this.provider.subtitle, it is not, what magic black vodo are you pulling ?

**Comment by vankasteelj** [comment]
I removed the subtitle provider from the top (that used to fetch subs as it was 'listing' available contents) by setting it to `undefined`, and instead made a per-content search based on IMDB, triggered inside `streamer.js`

**Comment by xaiki** [comment]
we have pluggable per provider defined subtitles providers, we should use that, your changes don't touch streamer.js are you sure you've got all commited ?

**Comment by vankasteelj** [comment]
I am sure. Just look for model.get('extractSubtitles') on streamer, that's where the magic happens

**Comment by xaiki** [comment]
your commit can't go in like this,
 * if you want to remove subtitles from generic_collection (debatable) we should remove all subtitle code, not just turn it into dead code.
 * that overloding of the movie model seems overkill, looking at the code it looks like only passing imdb_id should work
 * the way it's done doesn't allow for different subtitles providers for different providers, and we know that is wrong, we should use the provider info to suggest a sub provider
 * i don't see a way to pass a subtitle automatically from the provider.


my suggestion to go forward is:
 - add subtitles to the config of the providers
 - load subtitles providers the same way we load providers on demand in bootstrap so we catch errors early
 - keep the subtitles loading code in generic_collection, cache them but don't wait on them (i.e. keep a promise on them)
 - remove subtitles code from streamer as it seems like the wrong place for that.

**Comment by vankasteelj** [comment]
Opensubtitle can't be used as a provider: the API has a limit/ip. If you call OpenSubtitles for each item in Browser, you'll quickly hit the limit (I think it's 200 per 24h per IP, and 200 per 24h per account)

**Comment by vankasteelj** [comment]
More complete work is in xaiki/providers-opts

**Pull request closed without merging**
