### PR TITLE
migrate streamer and torrent_cache from popcorn-time, add torrent collection, add mass files drop, torrent collection path on settings

### PR DESCRIPTION
**Pull request by mike1pol**
migrate streamer and torrent_cache from popcorn-time, add torrent collection, add mass files drop, torrent collection path on settings

### CODE REVIEW

**Comment by xaiki** [comment]
a lot of whitespace changes... please fix those as this is impossible to review as is.
also split your changes in smoller commits...

**Comment by xaiki** [comment]
also we have decided to disable torrent collection for good reasons, please do not re-enable it before consulting.

**Comment by insertc0in** [comment]
@mike1pol
Translations should be submitted via Transifex as they will eventually overwrite the existing ones.
To participate in the translation project through Transifex, please go here: https://www.transifex.com/butterproject/public/

**Comment by MrAdder** [comment]
Unfortuanetly I am unable to merge this please Fix the things above before reopening the PR

**Pull request closed without merging**
