### PR TITLE
Switch to yarn using bower-away

### PR DESCRIPTION
**Pull request by yvan-sraka**
As advice on [Bower homepage](https://bower.io/):
> ...psst! While Bower is maintained, we recommend using [Yarn](https://yarnpkg.com/en/) and [Webpack](https://webpack.js.org/) for front-end projects [read how to migrate](https://bower.io/blog/2017/how-to-migrate-away-from-bower/)! 

Changes proposed in this pull request:
- Switch from `bower` to `yarn` using [bower-away](https://github.com/sheerun/bower-away)

I've read the [Contributor License Agreement](/CONTRIBUTING.md#contributor-license-agreement)

### CODE REVIEW

**Comment by FDiskas** [comment]
Keep away from yarn. Use npm. :boot:

**Comment by yvan-sraka** [comment]
But also remove depreciated `bower`dependency!

**Comment by btzr-io** [comment]
@yvan-sraka  Thanks for this awesome `PR`, 
I'm not sure what's the status of this project but 
if @xaiki have nothing to say / review I'll merge this in the next 24hrs.

**Comment by xaiki** [comment]
Awesome !

**Pull request merged**
