### PR TITLE
Add time-grunt to measure Grunt execution time

### PR DESCRIPTION
**Pull request by AdvancedCori**
Measuring the time taken for Grunt tasks to complete is quite useful insight. The package is well contained and shouldn't need any special attention.

### CODE REVIEW

**Comment by xaiki** [comment]
thanks a lot, let's get scared and switch to gulp =)

**Comment by AdvancedCori** [comment]
hehe, gulp would speed things up a lot

**Comment by 0tho** [comment]
Is gulp that much better and why?

**Comment by AdvancedCori** [comment]
- It's a lot faster than grunt as it uses node.js stream
- Prefers writing code over weird configs
- Better quality plugins (usually)

Or you know, we could go for [webpack](https://webpack.github.io/) instead. Just food for thought.

**Comment by xaiki** [comment]
patches are welcome (for gulp)

**Pull request merged**
