### PR TITLE
Update tr.json

### PR DESCRIPTION
**Pull request by PDirSG**
Fixes # .

Changes proposed in this pull request:
- 
- 
- 

I've read the [Contributor License Agreement](/CONTRIBUTING.md#contributor-license-agreement)

### CODE REVIEW

**Comment by xaiki** [comment]
@insertc0in shouldn't this go through transifex ?

**Comment by xaiki** [comment]
@insertc0in shouldn't this go through transifex ?

**Comment by insertc0in** [comment]
@xaiki Yes, this should definitely go through Transifex as all translations should.
Also, that information should be added to the README.

Unfortunately I have been very short on time, as you may have noticed from my continued absence; for this reason I don't imagine that I'll be able to contribute much in the near future.

**Comment by insertc0in** [comment]
@PDirSG If possible, please join the translation project over at Transifex: https://www.transifex.com/butterproject/butter-desktop/

Then you can submit the changes to your language: https://www.transifex.com/popcorn-time/popcorn-time-app/translate/#tr/desktop/31665326

**Comment by PDirSG** [comment]
Okay, i will. Thanks.

**Pull request closed without merging**
