### PR TITLE
use minified versions of js files

### PR DESCRIPTION
**Pull request by ZakariaRidouh**
This change *should* help load times.

### CODE REVIEW

**Comment by 0tho** [comment]
Does not the code get minified during build?

**Comment by ZakariaRidouh** [comment]
@0tho Im not sure about that

**Comment by vankasteelj** [comment]
yeah, it's not minified. But the proper fix would be to have a good way of shipping only those .min.js instead of everything like it's now. bower-exlude is bad (and it should feel bad)

**Comment by ZakariaRidouh** [comment]
Yeah I'll see what I can do to remove all the Bower Components junk (speaking of Bower, please have a look at issue #306)

See, it DID improve the load times :smile:

**Comment by ZakariaRidouh** [comment]
Ok I'll see what I can do :smile:

Speaking of Bower Components, can you have a look at issue #306

Thanks!

**Comment by ZakariaRidouh** [comment]
@vankasteelj Any news about when the project will start using Gulp? (the popcorn time fork of butter is using it now in development). I can get gulp to minify and concatenate all of the JS files into one main minified. Thanks!

**Comment by xaiki** [comment]
as @vankasteelj said that is not what's making loading slow, our DB code is, but if you want to take on migrating to gulp it's very welcome. cheers.

**Comment by 0tho** [comment]
@ZakariaRidouh I am currently migrating from grunt to gulp on my fork, still have some tasks to migrate like "grunt package" and "grunt dist", remove grunt entirely and test everything again. Could you give me a hand on that and we could also remove bower as you suggested on an issue?

**Comment by vankasteelj** [comment]
It's better to split everything:
- 1 PR to use gulp
- 1 PR to remove grunt leftovers
- 1 PR to switch from bower
- etc.

I'll be glad to help, where do you need a hand?

**Comment by ZakariaRidouh** [comment]
@vankasteelj Awesome, it seems like @0tho is currently working on moving to gulp on his gulp branch (https://github.com/0tho/butter-desktop/tree/gulp). 
I'll push some code there to minify all the DB files with gulp.

About the Bower leftovers, i'll submit a PR soon to (attempt) fixing them so they can make it into production as soon as possible :smile: 

Oh yeah, about the npm switch ill follow your advice and do the 1 commit each. I'll ping you if I need any help on the transition.

Thanks!

**Comment by ZakariaRidouh** [comment]
@vankasteelj found this nifty little tool: https://github.com/blittle/bower-installer

**Pull request merged**
