### PR TITLE
Update chromecast dependency

### PR DESCRIPTION
**Pull request by alxhotel**

### CODE REVIEW

**Comment by xaiki** [comment]
so this doesn't work ? what's chromecast-api ? is it a fork from the former chromecast-js code ?

**Comment by alxhotel** [comment]
Yeah it works, but I didn't make a "one commit + justification" so I thought I should close it.

Chromecast-api is a fork from chromecast-js with a few fixes and changes in functionality.

**Comment by xaiki** [comment]
@alxhotel please do a proper fork, keeping in your history former history (i.e. git clone and apply your patches) if you need help we can get you setup.

**Comment by alxhotel** [comment]
@xaiki I made a PR to the chromecast-js repo, but when I saw the last commit was of last year's April and there were some PRs with no answer at all, I thought I should create a new repo with my implementation.

**Pull request closed without merging**
