### PR TITLE
Greek translation improvements

### PR DESCRIPTION
**Pull request by sopex**
Fixes # .

Changes proposed in this pull request:
- The translation now makes sense
- 
- 

I've read the [Contributor License Agreement](/CONTRIBUTING.md#contributor-license-agreement)
I improved the greek translation. Some translations didn't make sense.

### CODE REVIEW

**Comment by xaiki** [comment]
hey thanks for your PR ! but translations are handled throuh transifex ! please coordinate with @insertc0in for those

**Comment by sopex** [comment]
@xaiki Do you prefer to make the some extra changes to transifex or here?

**Comment by xaiki** [comment]
sopex, i prefer we do them on transifex as it overwrittes our translations. 
that said i need to figure out how that works to be honest

**Comment by sopex** [comment]
@xaiki Just to know every single word of greek translation is in the wrong form so I have to change the 80% of the file and its a bit difficult in transifex. So if you can deactivate greek from transifex to don't overwrite the files.

**Comment by insertc0in** [comment]
@sopex Thanks for your contribution. 
Unfortunately, as @xaiki has explained, translations are not directly commited to the source. Instead we ask translators/contributors to use Transifex, which is from where we pull them. Looking at your commit I see that you made 13 changes, which does not seem that big of a stretch to do in Transifex. We would appreciate a ton if you could do it there, we don't really want to disturb the current feng shui we have going on. Thanks for your understanding.

**Comment by xaiki** [comment]
@insertc0in can you push this to transifex and make sure that PR is closed when done please ?

**Comment by insertc0in** [comment]
@xaiki, currently I am still waiting for @sopex to reply to my request about implementing it in Transifex. I don't see a reason to push 13 strings into Transifex, worst case I'll copy/paste them myself since it would bring less complications.

**Comment by xaiki** [comment]
great thanks, let's say that if we don't get an update by next week we'll handle that this way ?

**Comment by insertc0in** [comment]
Sure, no problem.

**Comment by insertc0in** [comment]
I've copied the changes in this PR into Transifex.
Further changes MUST be handled through there. Thanks @sopex for the contribution.

**Pull request closed without merging**
