### PR TITLE
use external file for configuration

### PR DESCRIPTION
**Pull request by vankasteelj**
- benefits: easier to maintain & change to 'our' api keys
- inconvenients: a new js file to load + global variables

### CODE REVIEW

**Comment by xaiki** [comment]
we already have that, if you drop a butter-settings-x package in your node_modules we'll load that and overload settings with whatever you have there.

**Comment by xaiki** [comment]
https://github.com/butterproject/butter-desktop/blob/master/src/app/bootstrap.js#L70

**Comment by vankasteelj** [comment]
I'll have to check that, but what if it's loaded after the rest?

**Comment by xaiki** [comment]
it is loaded last, so that it overrides all

**Pull request closed without merging**
